'use client';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';

export default function DisclaimerPage() {
  return (
    <main style={{ minHeight: '100vh', background: '#f5f5f4' }}>
      <SiteHeader />
      <div style={{ maxWidth: 800, margin: '0 auto', padding: '32px 24px' }}>
        <h1 style={{ fontSize: 24, fontWeight: 700, marginBottom: 4 }}>Data & Analysis Disclaimer</h1>
        <p style={{ fontSize: 13, color: '#888', marginBottom: 24 }}>Last updated: June 9, 2026 · Beta</p>

        <div style={{ background: '#fff', border: '1px solid #e5e5e5', borderRadius: 14, padding: '24px 28px', fontSize: 13, color: '#404040', lineHeight: 1.8 }}>
          <h2 style={{ fontSize: 16, fontWeight: 600, marginTop: 0, marginBottom: 8 }}>What Dissekt is — and isn't</h2>
          <p>Dissekt shows you HOW content is constructed. It identifies rhetorical techniques, cross-references existing fact-checks, and offers alternative framings. It does NOT tell you what is true or false. It is an interpretation aid, not an arbiter of truth.</p>

          <h2 style={{ fontSize: 16, fontWeight: 600, marginTop: 20, marginBottom: 8 }}>Automated analysis limitations</h2>
          <p>Our analysis is generated by AI models (GPT-4o mini, Claude) and statistical heuristics. These systems can and do make mistakes. They may: misidentify techniques, miss context, over- or under-state confidence, or produce results that reflect the biases of their training data. Always apply your own critical judgment.</p>

          <h2 style={{ fontSize: 16, fontWeight: 600, marginTop: 20, marginBottom: 8 }}>Political content (Compass)</h2>
          <p>Our political accountability data (Compass) is curated from public sources and may be incomplete or outdated. Politician profiles, voting records, and "factual notes" are provided for context only and should be independently verified. We do not endorse any political position.</p>

          <h2 style={{ fontSize: 16, fontWeight: 600, marginTop: 20, marginBottom: 8 }}>Source credibility (Signal)</h2>
          <p>Source bias and factuality ratings are derived from third-party databases (Media Bias/Fact Check). These ratings are themselves subjective assessments and should not be treated as definitive. The presence of a credibility score does not constitute an endorsement or condemnation of any source.</p>

          <h2 style={{ fontSize: 16, fontWeight: 600, marginTop: 20, marginBottom: 8 }}>Coordination detection (Pulse)</h2>
          <p>Coordination signals suggest patterns of similar content appearing together. This does NOT prove that content is coordinated, false, or malicious. Legitimate content can spread organically and still trigger these signals.</p>

          <h2 style={{ fontSize: 16, fontWeight: 600, marginTop: 20, marginBottom: 8 }}>Cross-references (Trace)</h2>
          <p>We surface existing fact-checks from third-party organizations. We do not create these fact-checks and are not responsible for their accuracy. A fact-check appearing in our results is not an endorsement of that fact-check's conclusion.</p>

          <h2 style={{ fontSize: 16, fontWeight: 600, marginTop: 20, marginBottom: 8 }}>No liability</h2>
          <p>You use Dissekt's analysis at your own risk. We are not liable for any decisions, actions, or consequences resulting from reliance on our analysis. For important matters, consult qualified professionals and primary sources.</p>

          <h2 style={{ fontSize: 16, fontWeight: 600, marginTop: 20, marginBottom: 8 }}>Beta status</h2>
          <p>Dissekt is in active beta development. Accuracy, features, and availability are not guaranteed. Data may be lost, reset, or changed during development.</p>
        </div>
      </div>
      <SiteFooter />
    </main>
  );
}
